// This file is autogenerated via the `commonjs` Grunt task. You can require() this file in a CommonJS environment.
require('../../js/transition.js')
require('../../js/alert.js')
require('../../js/button.js')
require('../../js/carousel.js')
require('../../js/collapse.js')
require('../../js/dropdown.js')
require('../../js/modal.js')
require('../../js/tooltip.js')
require('../../js/popover.js')
require('../../js/scrollspy.js')
require('../../js/tab.js')
require('../../js/affix.js')

register.js
//用户注册
$(document).ready(function () {
    $("#login-submit").click(function () {

        var name = $.trim($("#name").val());
        var password = $.trim($("#password").val());

        $.ajax({
            type:"POST",
            url:"/article/index.php/Register/resetRegister",
            data:{
                name :name,
                password :password,
            },
            dataType:"json",
            success:function (data) {

                if(data.code == 1){
                    alert('注册成功！');
                    window.location.href="/article/index.php/Admin/homePage";

                }else {
                    alert(data.msg);
                    $('#code-img').click();
                }

            },
            error:function (jqXHR) {
                alert("发生错误：" + jqXHR.status);
            }
        });
    });
});